# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from source.ShikiOAuth import ShikiOAuth
from PyQt5 import QtCore, QtGui, QtWidgets
from source.FormFunctions import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tbl_rates = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_rates.setEnabled(False)
        self.tbl_rates.setObjectName("tbl_rates")
        self.tbl_rates.setColumnCount(4)
        self.tbl_rates.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rates.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rates.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rates.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rates.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tbl_rates, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.led_anime_search = QtWidgets.QLineEdit(self.centralwidget)
        self.led_anime_search.setEnabled(False)
        self.led_anime_search.setObjectName("led_anime_search")
        self.gridLayout.addWidget(self.led_anime_search, 1, 1, 1, 1)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setEnabled(False)
        self.btn_search.setObjectName("btn_search")
        self.gridLayout.addWidget(self.btn_search, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.cbx_anime_search = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_anime_search.setEnabled(True)
        self.cbx_anime_search.setObjectName("cbx_anime_search")
        self.gridLayout.addWidget(self.cbx_anime_search, 2, 1, 1, 2)
        self.btn_add_rate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_rate.setEnabled(False)
        self.btn_add_rate.setObjectName("btn_add_rate")
        self.gridLayout.addWidget(self.btn_add_rate, 3, 1, 1, 1)
        self.btn_delete_rate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_rate.setEnabled(False)
        self.btn_delete_rate.setObjectName("btn_delete_rate")
        self.gridLayout.addWidget(self.btn_delete_rate, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menu_account = QtWidgets.QMenu(self.menubar)
        self.menu_account.setObjectName("menu_account")
        MainWindow.setMenuBar(self.menubar)
        self.action_log_in = QtWidgets.QAction(MainWindow)
        self.action_log_in.setObjectName("action_log_in")
        self.action_log_out = QtWidgets.QAction(MainWindow)
        self.action_log_out.setObjectName("action_log_out")
        self.menu_account.addAction(self.action_log_in)
        self.menu_account.addAction(self.action_log_out)
        self.menubar.addAction(self.menu_account.menuAction())

        self.tbl_rates.setColumnWidth(0, 650)
        self.tbl_rates.setColumnWidth(1, 80)
        self.tbl_rates.setColumnWidth(2, 80)
        self.tbl_rates.setColumnWidth(3, 80)
        self.tbl_rates.setEnabled(False)

        self.shiki = None
        tokens = ShikiOAuth.load_token()
        if tokens != None:
            self.shiki = Shikimori(tokens['access_token'], tokens['refresh_token'] )
            FormFunctions.update_table(self.tbl_rates, self.shiki)
            for arg in [self.tbl_rates, self.led_anime_search, self.btn_add_rate, self.btn_delete_rate, self.btn_search]:
                arg.setEnabled(True)

        
        self.add_functions()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шикимори"))
        item = self.tbl_rates.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tbl_rates.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Оценка"))
        item = self.tbl_rates.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Эпизоды"))
        item = self.tbl_rates.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Тип"))
        self.label.setText(_translate("MainWindow", "Поиск"))
        self.led_anime_search.setPlaceholderText(_translate("MainWindow", "Введите название"))
        self.btn_search.setText(_translate("MainWindow", "Поиск"))
        self.label_2.setText(_translate("MainWindow", "Результат"))
        self.btn_add_rate.setText(_translate("MainWindow", "Добавить"))
        self.btn_delete_rate.setText(_translate("MainWindow", "Удалить"))
        self.menu_account.setTitle(_translate("MainWindow", "Аккаунт"))
        self.action_log_in.setText(_translate("MainWindow", "Войти"))
        self.action_log_out.setText(_translate("MainWindow", "Выйти"))

    def add_functions(self):
        self.btn_search.clicked.connect(lambda: FormFunctions.evt_search_anime_clicked(self.led_anime_search, self.cbx_anime_search, self.shiki))
        self.btn_add_rate.clicked.connect(lambda: FormFunctions.evt_create_rate_clicked(self.tbl_rates, self.cbx_anime_search, self.shiki))
        self.btn_delete_rate.clicked.connect(lambda: FormFunctions.evt_delete_rate_clicked(self.tbl_rates, self.shiki))
        self.tbl_rates.itemChanged.connect(lambda: FormFunctions.evt_change_rate_changed(self.tbl_rates, self.shiki))
        self.action_log_in.triggered.connect(lambda: FormFunctions.evt_authorization_clicked(MainWindow, self.shiki, self.tbl_rates, self.led_anime_search, self.btn_add_rate, self.btn_delete_rate, self.btn_search))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
